### PR TITLE
List structure

### PR DESCRIPTION
**Pull request by petumazo**
For this milestone:

- Create index.html 
- Create index.js
  - Create Task class.
  - Create ToDoList class.
  - Create methods to add a task and render the list of tasks.
- Use the bootstrap library for major styling.
- Create style.css for styling details.
- Use the localStorage to store the data.

### CODE REVIEW

**Review by abruzy — CHANGES_REQUESTED** [review]
Hi @petumazo 👋🏽, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
_1. When I run the `npm run start` command I get this error, please check the screenshot below._

Screenshot 2021-08-19 at 04 15 33

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by petumazo** [comment]
> Hi @petumazo 👋🏽,
> 
> Good job so far!
> There are some issues that you still need to work on to go to the next project but you are almost there!
> ## Required Changes ♻️
> _1. When I run the `npm run start` command I get this error, please check the screenshot below._
> 
> Screenshot 2021-08-19 at 04 15 33
> 
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> You can also consider:
> 
> * N/A
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

@abruzy Thanks for the feedback, I corrected the error.

**Review by dasileker — CHANGES_REQUESTED** [review]
### **Hi  @petumazo,** 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._


- The node_modules is not correctly added

- The npm start is not working, so please fix it.
nn


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by SpaYco** [comment]
Hello 👋,

_This is an additional review as a result of the second opinion request._

I'm also getting the same error, deleting `node_modules` and reinstalling fixed it but still got another error, the problem is with how the webpack is configured, please fix it and make sure to configure it for all modes, not just development, try asking a friend to test the new changes before making another code review, to make sure that it works this time!

Keep rocking 🚀!

**Comment by petumazo** [comment]
Thanks for the feedback, after multiple attempts to replicate the error, the project was done it again from scratches. I did multiple tests, and share the repo with 4 different partners to check that it works.

**Review by bellom — APPROVED** [review]
## Hi @petumazo  👏  

**Great work making all the necessary corrections from the previous review.**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
